# Generated by Django 3.1.3 on 2022-01-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211227_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
    ]
