# Generated by Django 3.1.3 on 2022-01-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220125_1156'),
        ('user', '0003_auto_20220125_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
