# Generated by Django 3.1.3 on 2021-12-16 17:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('buttontext', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/carousel/img')),
                ('link', models.CharField(blank=True, max_length=250)),
                ('carousel_order', models.IntegerField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SignInCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/signinupcarousel')),
                ('carousel_order', models.IntegerField(blank=True)),
                ('talent_appreciation_text', models.CharField(blank=True, max_length=70)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/signinupcarousel')),
                ('carousel_order', models.IntegerField(blank=True)),
                ('talent_appreciation_text', models.CharField(blank=True, max_length=70)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('primary_skill', models.CharField(max_length=50)),
                ('primary_skill_other', models.CharField(blank=True, max_length=50)),
                ('secondary_skills', models.CharField(blank=True, max_length=50)),
                ('engagement', models.CharField(max_length=20)),
                ('is_trained', models.BooleanField()),
                ('availability', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('will_travel', models.BooleanField()),
                ('price', models.CharField(max_length=20)),
                ('price_rate', models.CharField(max_length=50)),
                ('provide_training', models.BooleanField()),
                ('instagram_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('twitter_url', models.URLField()),
            ],
        ),
    ]
