# Generated by Django 3.1.3 on 2022-01-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220125_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/store/logo/'),
        ),
    ]
