# Generated by Django 3.1.3 on 2022-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentuser',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='media/talentprofile/img/thumbnail'),
        ),
    ]
